[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bytes = "1"
error-chain = "0.12"
futures = "0.3"
nom = "6"
rand = "0.8"
rayon = "1"
reqwest = "0.11"
rmp-serde = "0.15"
rodio = { git = "https://github.com/RustAudio/rodio.git" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.9"
tokio = { version = "1", features = ["full"] }
twoway = "0.2"


[features]
default = ["playback"]
playback = []
