[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.5.0"
async-trait = "0.1.30"
bytes = "0.5.4"
futures = "0.3.4"
nom = "5.1.1"
rand = "0.7.3"
rayon = "1.3.0"
reqwest = "0.10.4"
rmp-serde = "0.14.3"
rodio = "0.11.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
sha2 = "0.8.1"
twoway = "0.2.1"

[dev-dependencies]
tokio = { version = "0.2.18", features = ["full"] }
