[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2021"
publish = false

[features]
default = ["fs", "playback", "rayon", "rodio/mp3", "rodio/wav"]
playback = []
fs = ["tokio"]
wasm = ["getrandom/js", "rodio/wasm-bindgen"]

[dependencies]
bytes = "1"
futures = "0.3"
getrandom = "0.2"
nom = "7"
quick-error = "2"
rand = "0.8"
rayon = { version = "1", optional = true }
reqwest = "0.11"
rmp-serde = "1"
rodio = { version = "0.15", default-features = false, features = ["vorbis"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["fs", "macros"], optional = true }
twoway = "0.2"
