[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
bytes = "0.5"
error-chain = "0.12.4"
futures = "0.3.8"
nom = "6.0.1"
rand = "0.7.3"
rayon = "1.5.0"
reqwest = "0.10.9"
rmp-serde = "0.14.4"
rodio = { git = "https://github.com/RustAudio/rodio.git" }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
sha2 = "0.9.2"
tokio = { version = "0.2", features = ["full"] }
twoway = "0.2.1"


[features]
default = ["playback"]
playback = []
