[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
reqwest = "0.9.21"
rmp-serde = "0.14.0"
rodio = "0.9.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
sha2 = "0.8.0"
