[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.40"
bytes = "0.5.6"
error-chain = "0.12.4"
futures = "0.3.5"
nom = "5.1.2"
rand = "0.7.3"
rayon = "1.4.0"
reqwest = "0.10.8"
rmp-serde = "0.14.4"
rodio = { git = "https://github.com/RustAudio/rodio.git" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
sha2 = "0.9.1"
tokio = { version = "0.2.22", features = ["full"] }
twoway = "0.2.1"
