[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.6.2"
async-trait = "0.1.36"
bytes = "0.5.5"
error-chain = "0.12.2"
futures = "0.3.5"
nom = "5.1.2"
rand = "0.7.3"
rayon = "1.3.1"
reqwest = "0.10.6"
rmp-serde = "0.14.3"
rodio = "0.11.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
sha2 = "0.9.0"
twoway = "0.2.1"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["full"] }
