[package]
name = "chatsounds"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.10"
async-trait = "0.1.16"
bytes = "0.4.12"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
rayon = "1.2.0"
reqwest = "0.10.0-alpha.1"
rmp-serde = "0.14.0"
rodio = "0.9.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
sha2 = "0.8.0"
twoway = "0.2.1"

[dev-dependencies]
tokio = "0.2.0-alpha.6"
