name: Release

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # do not cancel in-progress jobs

permissions: {} # none, since we use a custom app

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@14f3ff0a30de650ab794eecf41a03f1f9d702822 # main
    with:
      package-name: chatsounds
      replace-files: |
        Cargo.lock
        Cargo.toml
    secrets:
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
