name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # do not cancel in-progress jobs

permissions: {} # none, since we use a custom app

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@865465524134a84dcf3b16cbaa4dde492ad866ee # main
    with:
      package-name: chatsounds
      replace-files: |
        Cargo.lock
        Cargo.toml
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
