name: Update lock files

on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

concurrency:
  group: update-lock-files-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_lock_files:
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-lock-files.yml@2169b6df8bbbd52912f8ed3f4afb32782398b695 # main
    with:
      rust-attribute: default
