name: Update lock files

on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

concurrency:
  group: update-lock-files-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_lock_files:
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-lock-files.yml@355f43206c36e56e1608ad5f5766a82e54c673a5 # main
    with:
      rust-attribute: default
